apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rag-app.fullname" . }}-secret
  labels:
    {{- include "rag-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_URL: {{ .Values.secret.DB_URL | quote }}
  LLM_API_KEY: {{ .Values.secret.LLM_API_KEY | quote }}
